#!/usr/local/bin/node
'use strict';

/**
 * Command-line interface which initiates the frame software.
 */

var jsonfile = require('jsonfile'),
    FrameController = require('./controller');

var ofrc_file = './.ofrc';

// open plugins file
jsonfile.readFile(ofrc_file, function(err, ofrc) {
    if (err) {
        console.error(err);
        return;
    }
    var auth = ofrc.auth;

    if (!auth || !auth.email || !auth.password) {

    }

    config('username', program.username);
    config('framename', program.framename);
});

// instantiate the frame controller
var FC = new FrameController();
